6.18. Микросетки на флексах для всех страниц
htmlacademy-htmlcss/2071821-sedona-35 pull request #6
Opened 2022-10-24 14:46 UTC by Olgartlab

В этом задании не разобралась, как подвинуть эелементы в правый край контейнера  navigation-user в header и 
как позиционировать select-control. Может лучше сделать catalog-sorting гридами?

2022-10-25 08:28 UTC, andreysgra requested changes

2022-10-25 08:28 UTC, andreysgra commented on styles/styles.css
>    margin-left: auto;
Давайте разберёмся, почему вам не удалось подвинуть, как вы говорите, `.navigation-user` вправо.

На самом деле этот блок сдвинут вправо до границы родительского блока `.navigation`. Это можно увидеть в Dev Tools:
![image](https://user-images.githubusercontent.com/17790771/197713526-2ca6af94-0a12-4824-a558-526eb94482c7.png)
Заштрихованный фиолетовый прямоугольник это свободное, нераспределённое пространство в `.navigation-user`. По умолчанию выравнивание во флекс-контейнере происходит от начала главной оси `justify-content: flex-start` и соответственно все три элемента списка `.navigation-user` так и выровнялись. Последним идёт свободное пространство. Откуда оно взялось?
Ширина, которую вы задали `.navigation-user` равна 310px, но судя по макету она явно меньше:
![image](https://user-images.githubusercontent.com/17790771/197715258-b9eed9c2-ae32-4f80-86b4-b8dcb0307b92.png)

Но если для блока ширина нужна больше, чем в макете (здесь это не нужно) направление выравнивания контента можно изменить с помощью свойства `justify-content`.

2022-10-25 08:28 UTC, andreysgra commented on styles/styles.css
>  .select-control{
Вы спрашиваете, как позиционировать `.select-control`. Можно также, как и `view-wrapper` с помощью `margin-left: auto`, но думаю, что лучше задать для `margin-left` конкретное значение в `px`. Но для этого нужно сначала определиться с шириной элемента `search-result`. Сейчас у вас его ширина не задана и если добавить в него ещё текста, то будут сдвигаться элементы справа от него:
![image](https://user-images.githubusercontent.com/17790771/197717538-9299602e-7e33-4a63-a3d4-422730eb4166.png)

Также нужно задать максимально возможную ширину для блока `view-wrapper` иначе при добавлении кнопок будет происходить сдвиг контента слева от него:
![image](https://user-images.githubusercontent.com/17790771/197718035-9b494452-554a-46d4-a8b5-ff8d5ad7fe29.png)

Из всего этого следует вывод, что недостаточно элементу задать свойство `display: flex` чтобы построить надёжную сетку внутри него.

Можно раскладку в этом блоке сделать и с помощью `grid`, но вы не получите никаких преимуществ, если блоку `catalog-sorting` просто зададите `display: grid`. Нужно будет задать шаблон для колонок.

2022-10-25 08:28 UTC, andreysgra commented on styles/styles.css
> +  min-height: 20px;
Можно и даже лучше вместо `min-width` и `min-height` использовать `width` и `height`. В этих элементах нет текстового контента, а размеры иконок не должны изменяться.

2022-10-25 08:28 UTC, andreysgra commented on styles/styles.css
> +  padding-right: 85px;
Я бы посоветовал вместо паддингов для конкретного элемента сделать паддинги в родительском элементе. Причём эти паддинги должны быть не только слева и справа, но и сверху и снизу. Примерно так:
![image](https://user-images.githubusercontent.com/17790771/197721818-51a8d5b7-53e0-4040-a86a-cd1ff5264df0.png)

Это касается всех квадратных блоков внутри секции `advantages`.

2022-10-25 08:28 UTC, andreysgra commented on styles/styles.css
> +  min-height: 17px;
Для ссылок соцсетей тоже лучше использовать свойства `width` и `height`.

2022-10-25 15:29 UTC, Olgartlab commented on styles/styles.css
>    margin-left: auto;
Спасибо за подробный разбор. 
Я пересмотрела еще раз скрин каст академии, т к  я ориентировалась по нему. Ширина блоков навигации задается больше, чем на макете, чтобы учесть возможное появление еще одного элемента, а
элементы списка .navigation-user в скарин касте тоже имеют свободное пространство справа. 
В итоге я оставила размеры блоков "на вырост" и использовала свойство justify-content.

2022-10-25 15:35 UTC, Olgartlab commented on styles/styles.css
> +  min-height: 20px;
Следовала рекомендациям из скрин каста. Предполагалось, что вместо иконки может таки появиться текст.
Все-таки лучше зафиксровать размеры?

2022-10-25 17:02 UTC, Olgartlab commented on styles/styles.css
> +  padding-right: 85px;
Сделала паддинги у родителей. 
У квадратных блоков с иконками другие паддинги.  Задала их по классу. Не слишком много классов получилось?

2022-10-26 08:26 UTC, andreysgra commented on styles/styles.css
> +  min-height: 20px;
Если по дизайну в элементе текст не предполагается, то стоит задавать фиксированные размеры. Но можете оставить, как есть.

2022-10-26 08:36 UTC, andreysgra commented on styles/styles.css
> +  padding-right: 85px;
Кроме паддингов нужно задать `box-sizing: border-box`. Здесь мы видим, что ширина блока превышает 400px:
![image](https://user-images.githubusercontent.com/17790771/197975331-a4c4575b-0316-451e-8233-e108f5534fa4.png)
Держится всё лишь потому, что `blue-item-text` находится внутри флекс-контейнера и является флекс-элементом, а значит на него действуют правила флекс и флекс-элемент сжимается, пока ему позволяет доступное пространство. Однако, если бы здесь была использована блочная модель, то `blue-item-text` просто бы "распёрло".

При расчёте общей ширины блока (по умолчанию `box-sizing` равно `content-box`) к `width` добавляется `padding-left` и `padding-right`, так что при `width: 400px`, `padding-left: 85px`, `padding-right: 85px` ширина составит 570px.

2022-10-26 08:37 UTC, merged